# Generated by Django 3.2.7 on 2021-10-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_geo_burkina', '0002_auto_20211004_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departements',
            name='departements',
        ),
        migrations.AddField(
            model_name='departements',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='api_geo_burkina.provinces'),
        ),
    ]
